apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployName }}-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployName }}-back
  template:
    metadata:
      labels:
        app: {{ .Values.deployName }}-back
    spec:
      containers:
        - name: {{ .Values.deployName }}-back
          image: nicodev28/img-back:latest
          resources:
            limits:
              cpu: "0.1"
              memory: "64Mi"
            requests:
              cpu: "50m"
              memory: "32Mi"
          ports:
            - containerPort: 5000
