apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployName }}-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployName }}-front
  template:
    metadata:
      labels:
        app: {{ .Values.deployName }}-front
    spec:
      containers:
        - name: {{ .Values.deployName }}-front
          image: nicodev28/img-front:latest
          envFrom:
          - configMapRef:
              name: {{ .Values.configMapName }}
          resources:
            limits:
              cpu: "0.1"
              memory: "64Mi"
            requests:
              cpu: "50m"
              memory: "32Mi"
          ports:
            - containerPort: 80

