apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployName }}-front-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.deployName }}-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80