apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployName }}-back-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deployName }}-back
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000